<?php

namespace ContainerJkRcFVI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UYEsSNBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uYEsSNB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uYEsSNB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'modePaimentRepository' => ['privates', 'App\\Repository\\ModePaimentRepository', 'getModePaimentRepositoryService', true],
        ], [
            'modePaimentRepository' => 'App\\Repository\\ModePaimentRepository',
        ]);
    }
}
