<?php

namespace ContainerJkRcFVI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K_Hq8WjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.K.hq8Wj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.K.hq8Wj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'heureSuplementaire' => ['privates', '.errored..service_locator.K.hq8Wj.App\\Entity\\HeureSuplementaire', NULL, 'Cannot autowire service ".service_locator.K.hq8Wj": it needs an instance of "App\\Entity\\HeureSuplementaire" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'heureSuplementaire' => 'App\\Entity\\HeureSuplementaire',
        ]);
    }
}
