<?php

namespace ContainerJkRcFVI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VD2sxzIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vD2sxzI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vD2sxzI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'modePaiment' => ['privates', '.errored..service_locator.vD2sxzI.App\\Entity\\ModePaiment', NULL, 'Cannot autowire service ".service_locator.vD2sxzI": it needs an instance of "App\\Entity\\ModePaiment" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'modePaiment' => 'App\\Entity\\ModePaiment',
        ]);
    }
}
