<?php

namespace ContainerJkRcFVI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EMFrWn2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eMFrWn2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eMFrWn2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cvCandidatNote' => ['privates', '.errored..service_locator.eMFrWn2.App\\Entity\\CvCandidatNote', NULL, 'Cannot autowire service ".service_locator.eMFrWn2": it needs an instance of "App\\Entity\\CvCandidatNote" but this type has been excluded in "config/services.yaml".'],
        ], [
            'cvCandidatNote' => 'App\\Entity\\CvCandidatNote',
        ]);
    }
}
