<?php

namespace ContainerJkRcFVI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B9f9hjDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B9f9hjD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B9f9hjD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cVRequirement' => ['privates', '.errored..service_locator.B9f9hjD.App\\Entity\\CVRequirements', NULL, 'Cannot autowire service ".service_locator.B9f9hjD": it needs an instance of "App\\Entity\\CVRequirements" but this type has been excluded in "config/services.yaml".'],
        ], [
            'cVRequirement' => 'App\\Entity\\CVRequirements',
        ]);
    }
}
