<?php

namespace ContainerJkRcFVI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SeBRg_LService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.seBRg.L' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.seBRg.L'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'diplome' => ['privates', '.errored..service_locator.seBRg.L.App\\Entity\\Diplome', NULL, 'Cannot autowire service ".service_locator.seBRg.L": it needs an instance of "App\\Entity\\Diplome" but this type has been excluded in "config/services.yaml".'],
        ], [
            'diplome' => 'App\\Entity\\Diplome',
        ]);
    }
}
