<?php

namespace ContainerJkRcFVI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VIhsdQkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VIhsdQk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VIhsdQk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'diplome' => ['privates', '.errored..service_locator.VIhsdQk.App\\Entity\\Diplome', NULL, 'Cannot autowire service ".service_locator.VIhsdQk": it needs an instance of "App\\Entity\\Diplome" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'diplome' => 'App\\Entity\\Diplome',
            'entityManager' => '?',
        ]);
    }
}
