<?php

namespace ContainerJkRcFVI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EdYJepgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.edYJepg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.edYJepg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'experience' => ['privates', '.errored..service_locator.edYJepg.App\\Entity\\Experience', NULL, 'Cannot autowire service ".service_locator.edYJepg": it needs an instance of "App\\Entity\\Experience" but this type has been excluded in "config/services.yaml".'],
        ], [
            'experience' => 'App\\Entity\\Experience',
        ]);
    }
}
