<?php

namespace ContainerJkRcFVI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SB7vVTcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SB7vVTc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SB7vVTc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cVCandidatRepository' => ['privates', 'App\\Repository\\CVCandidatRepository', 'getCVCandidatRepositoryService', true],
            'cVRequirementsRepository' => ['privates', 'App\\Repository\\CVRequirementsRepository', 'getCVRequirementsRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'cVCandidatRepository' => 'App\\Repository\\CVCandidatRepository',
            'cVRequirementsRepository' => 'App\\Repository\\CVRequirementsRepository',
            'entityManager' => '?',
        ]);
    }
}
