<?php

namespace ContainerJkRcFVI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yeq7fgYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yeq7fgY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yeq7fgY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'nationaliteRepository' => ['privates', 'App\\Repository\\NationaliteRepository', 'getNationaliteRepositoryService', true],
        ], [
            'nationaliteRepository' => 'App\\Repository\\NationaliteRepository',
        ]);
    }
}
