<?php

namespace ContainerJkRcFVI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9eH54lqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9eH54lq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9eH54lq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'domaine' => ['privates', '.errored..service_locator.9eH54lq.App\\Entity\\Domaine', NULL, 'Cannot autowire service ".service_locator.9eH54lq": it needs an instance of "App\\Entity\\Domaine" but this type has been excluded in "config/services.yaml".'],
        ], [
            'domaine' => 'App\\Entity\\Domaine',
        ]);
    }
}
