<?php

namespace ContainerJkRcFVI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CdaGiE4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CdaGiE4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CdaGiE4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cVCandidat' => ['privates', '.errored..service_locator.CdaGiE4.App\\Entity\\CVCandidat', NULL, 'Cannot autowire service ".service_locator.CdaGiE4": it needs an instance of "App\\Entity\\CVCandidat" but this type has been excluded in "config/services.yaml".'],
        ], [
            'cVCandidat' => 'App\\Entity\\CVCandidat',
        ]);
    }
}
