<?php

namespace ContainerJkRcFVI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dfahb06Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dfahb06' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dfahb06'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reponseSection' => ['privates', '.errored..service_locator.dfahb06.App\\Entity\\ReponseSection', NULL, 'Cannot autowire service ".service_locator.dfahb06": it needs an instance of "App\\Entity\\ReponseSection" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'reponseSection' => 'App\\Entity\\ReponseSection',
        ]);
    }
}
