<?php

namespace ContainerJkRcFVI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCvCandidatNote2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.eMFrWn2.App\Entity\CvCandidatNote' shared service.
     *
     * @return \App\Entity\CvCandidatNote
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.eMFrWn2": it needs an instance of "App\\Entity\\CvCandidatNote" but this type has been excluded in "config/services.yaml".');
    }
}
