<?php

namespace ContainerJkRcFVI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCVRequirementsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CVRequirementsController' shared autowired service.
     *
     * @return \App\Controller\CVRequirementsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CVRequirementsController.php';

        $container->services['App\\Controller\\CVRequirementsController'] = $instance = new \App\Controller\CVRequirementsController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\CVRequirementsController', $container));

        return $instance;
    }
}
