<?php

namespace ContainerJkRcFVI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMatrimonialeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7e.LYLE.App\Entity\Matrimoniale' shared service.
     *
     * @return \App\Entity\Matrimoniale
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.7e.LYLE": it needs an instance of "App\\Entity\\Matrimoniale" but this type has been excluded in "config/services.yaml".');
    }
}
