<?php

namespace ContainerJkRcFVI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModePaimentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8JF4GpG.App\Entity\ModePaiment' shared service.
     *
     * @return \App\Entity\ModePaiment
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8JF4GpG": it needs an instance of "App\\Entity\\ModePaiment" but this type has been excluded in "config/services.yaml".');
    }
}
