<?php

namespace ContainerJkRcFVI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReponseSection2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.dfahb06.App\Entity\ReponseSection' shared service.
     *
     * @return \App\Entity\ReponseSection
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.dfahb06": it needs an instance of "App\\Entity\\ReponseSection" but this type has been excluded in "config/services.yaml".');
    }
}
