<?php

namespace ContainerJkRcFVI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestResultat3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DRP9YXs.App\Entity\TestResultat' shared service.
     *
     * @return \App\Entity\TestResultat
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.DRP9YXs": it needs an instance of "App\\Entity\\TestResultat" but this type has been excluded in "config/services.yaml".');
    }
}
