<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Employe extends \App\Entity\Employe implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cnaps' => [parent::class, 'cnaps', null],
        "\0".parent::class."\0".'conges' => [parent::class, 'conges', null],
        "\0".parent::class."\0".'date_embauche' => [parent::class, 'date_embauche', null],
        "\0".parent::class."\0".'heuresuplementaire' => [parent::class, 'heuresuplementaire', null],
        "\0".parent::class."\0".'historiqueSalaires' => [parent::class, 'historiqueSalaires', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'osti' => [parent::class, 'osti', null],
        "\0".parent::class."\0".'poste' => [parent::class, 'poste', null],
        "\0".parent::class."\0".'salaire' => [parent::class, 'salaire', null],
        "\0".parent::class."\0".'service' => [parent::class, 'service', null],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null],
        "\0".parent::class."\0".'superieur' => [parent::class, 'superieur', null],
        "\0".parent::class."\0".'utilisateur' => [parent::class, 'utilisateur', null],
        'cnaps' => [parent::class, 'cnaps', null],
        'conges' => [parent::class, 'conges', null],
        'date_embauche' => [parent::class, 'date_embauche', null],
        'heuresuplementaire' => [parent::class, 'heuresuplementaire', null],
        'historiqueSalaires' => [parent::class, 'historiqueSalaires', null],
        'id' => [parent::class, 'id', null],
        'osti' => [parent::class, 'osti', null],
        'poste' => [parent::class, 'poste', null],
        'salaire' => [parent::class, 'salaire', null],
        'service' => [parent::class, 'service', null],
        'statut' => [parent::class, 'statut', null],
        'superieur' => [parent::class, 'superieur', null],
        'utilisateur' => [parent::class, 'utilisateur', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
