<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Nationalite extends \App\Entity\Nationalite implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cVCandidats' => [parent::class, 'cVCandidats', null],
        "\0".parent::class."\0".'cVRequirements' => [parent::class, 'cVRequirements', null],
        "\0".parent::class."\0".'code_nationalite' => [parent::class, 'code_nationalite', null],
        "\0".parent::class."\0".'des_nationalite' => [parent::class, 'des_nationalite', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        'cVCandidats' => [parent::class, 'cVCandidats', null],
        'cVRequirements' => [parent::class, 'cVRequirements', null],
        'code_nationalite' => [parent::class, 'code_nationalite', null],
        'des_nationalite' => [parent::class, 'des_nationalite', null],
        'id' => [parent::class, 'id', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
