<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CVRequirements extends \App\Entity\CVRequirements implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null],
        "\0".parent::class."\0".'cVCandidats' => [parent::class, 'cVCandidats', null],
        "\0".parent::class."\0".'coef_adresse' => [parent::class, 'coef_adresse', null],
        "\0".parent::class."\0".'coef_diplome' => [parent::class, 'coef_diplome', null],
        "\0".parent::class."\0".'coef_matrimoniale' => [parent::class, 'coef_matrimoniale', null],
        "\0".parent::class."\0".'coef_nationalite' => [parent::class, 'coef_nationalite', null],
        "\0".parent::class."\0".'coef_sexe' => [parent::class, 'coef_sexe', null],
        "\0".parent::class."\0".'coef_xp' => [parent::class, 'coef_xp', null],
        "\0".parent::class."\0".'date_envoie' => [parent::class, 'date_envoie', null],
        "\0".parent::class."\0".'date_fin' => [parent::class, 'date_fin', null],
        "\0".parent::class."\0".'diplome' => [parent::class, 'diplome', null],
        "\0".parent::class."\0".'domaine' => [parent::class, 'domaine', null],
        "\0".parent::class."\0".'experience' => [parent::class, 'experience', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'matrimoniale' => [parent::class, 'matrimoniale', null],
        "\0".parent::class."\0".'nationalite' => [parent::class, 'nationalite', null],
        "\0".parent::class."\0".'poste_description' => [parent::class, 'poste_description', null],
        "\0".parent::class."\0".'service' => [parent::class, 'service', null],
        "\0".parent::class."\0".'sexe' => [parent::class, 'sexe', null],
        "\0".parent::class."\0".'testAptitude' => [parent::class, 'testAptitude', null],
        'adresse' => [parent::class, 'adresse', null],
        'cVCandidats' => [parent::class, 'cVCandidats', null],
        'coef_adresse' => [parent::class, 'coef_adresse', null],
        'coef_diplome' => [parent::class, 'coef_diplome', null],
        'coef_matrimoniale' => [parent::class, 'coef_matrimoniale', null],
        'coef_nationalite' => [parent::class, 'coef_nationalite', null],
        'coef_sexe' => [parent::class, 'coef_sexe', null],
        'coef_xp' => [parent::class, 'coef_xp', null],
        'date_envoie' => [parent::class, 'date_envoie', null],
        'date_fin' => [parent::class, 'date_fin', null],
        'diplome' => [parent::class, 'diplome', null],
        'domaine' => [parent::class, 'domaine', null],
        'experience' => [parent::class, 'experience', null],
        'id' => [parent::class, 'id', null],
        'matrimoniale' => [parent::class, 'matrimoniale', null],
        'nationalite' => [parent::class, 'nationalite', null],
        'poste_description' => [parent::class, 'poste_description', null],
        'service' => [parent::class, 'service', null],
        'sexe' => [parent::class, 'sexe', null],
        'testAptitude' => [parent::class, 'testAptitude', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
