<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AGVRq48Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AGVRq48' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AGVRq48'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'testAptitude' => ['privates', '.errored..service_locator.AGVRq48.App\\Entity\\TestAptitude', NULL, 'Cannot autowire service ".service_locator.AGVRq48": it needs an instance of "App\\Entity\\TestAptitude" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'testAptitude' => 'App\\Entity\\TestAptitude',
        ]);
    }
}
