<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NXm5lUTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nXm5lUT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nXm5lUT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sectionReponseRepository' => ['privates', 'App\\Repository\\SectionReponseRepository', 'getSectionReponseRepositoryService', true],
        ], [
            'sectionReponseRepository' => 'App\\Repository\\SectionReponseRepository',
        ]);
    }
}
