<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N07EL_OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N07EL.o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N07EL.o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cvCandidatNoteRepository' => ['privates', 'App\\Repository\\CvCandidatNoteRepository', 'getCvCandidatNoteRepositoryService', true],
        ], [
            'cvCandidatNoteRepository' => 'App\\Repository\\CvCandidatNoteRepository',
        ]);
    }
}
