<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GUZPG5CService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GUZPG5C' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GUZPG5C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cVCandidat' => ['privates', '.errored..service_locator.GUZPG5C.App\\Entity\\CVCandidat', NULL, 'Cannot autowire service ".service_locator.GUZPG5C": it needs an instance of "App\\Entity\\CVCandidat" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'cVCandidat' => 'App\\Entity\\CVCandidat',
            'entityManager' => '?',
        ]);
    }
}
