<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hu0Pzs_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hu0Pzs.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hu0Pzs.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'domaine' => ['privates', '.errored..service_locator.hu0Pzs..App\\Entity\\Domaine', NULL, 'Cannot autowire service ".service_locator.hu0Pzs.": it needs an instance of "App\\Entity\\Domaine" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'domaine' => 'App\\Entity\\Domaine',
            'entityManager' => '?',
        ]);
    }
}
