<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HFck0TGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HFck0TG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HFck0TG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sexe' => ['privates', '.errored..service_locator.HFck0TG.App\\Entity\\Sexe', NULL, 'Cannot autowire service ".service_locator.HFck0TG": it needs an instance of "App\\Entity\\Sexe" but this type has been excluded in "config/services.yaml".'],
        ], [
            'sexe' => 'App\\Entity\\Sexe',
        ]);
    }
}
