<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DRP9YXsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DRP9YXs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DRP9YXs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'testResultats' => ['privates', '.errored..service_locator.DRP9YXs.App\\Entity\\TestResultat', NULL, 'Cannot autowire service ".service_locator.DRP9YXs": it needs an instance of "App\\Entity\\TestResultat" but this type has been excluded in "config/services.yaml".'],
        ], [
            'testResultats' => 'App\\Entity\\TestResultat',
        ]);
    }
}
