<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bhov_GaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bhov.Ga' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bhov.Ga'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'nationalite' => ['privates', '.errored..service_locator.bhov.Ga.App\\Entity\\Nationalite', NULL, 'Cannot autowire service ".service_locator.bhov.Ga": it needs an instance of "App\\Entity\\Nationalite" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'nationalite' => 'App\\Entity\\Nationalite',
        ]);
    }
}
