<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6m8pwjoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6m8pwjo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6m8pwjo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'testResultat' => ['privates', '.errored..service_locator.6m8pwjo.App\\Entity\\TestResultat', NULL, 'Cannot autowire service ".service_locator.6m8pwjo": it needs an instance of "App\\Entity\\TestResultat" but this type has been excluded in "config/services.yaml".'],
        ], [
            'testResultat' => 'App\\Entity\\TestResultat',
        ]);
    }
}
