<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rq1pLTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rq1pL_T' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rq1pL_T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reponseSectionRepository' => ['privates', 'App\\Repository\\ReponseSectionRepository', 'getReponseSectionRepositoryService', true],
        ], [
            'reponseSectionRepository' => 'App\\Repository\\ReponseSectionRepository',
        ]);
    }
}
