<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TvSoWeiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TvSoWei' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TvSoWei'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'articleFournisseur' => ['privates', '.errored..service_locator.TvSoWei.App\\Entity\\ArticleFournisseur', NULL, 'Cannot autowire service ".service_locator.TvSoWei": it needs an instance of "App\\Entity\\ArticleFournisseur" but this type has been excluded in "config/services.yaml".'],
        ], [
            'articleFournisseur' => 'App\\Entity\\ArticleFournisseur',
        ]);
    }
}
