<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DqpXpMtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DqpXpMt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DqpXpMt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sectionReponse' => ['privates', '.errored..service_locator.DqpXpMt.App\\Entity\\SectionReponse', NULL, 'Cannot autowire service ".service_locator.DqpXpMt": it needs an instance of "App\\Entity\\SectionReponse" but this type has been excluded in "config/services.yaml".'],
        ], [
            'sectionReponse' => 'App\\Entity\\SectionReponse',
        ]);
    }
}
