<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_84Au0WHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.84Au0WH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.84Au0WH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'articleFournisseur' => ['privates', '.errored..service_locator.84Au0WH.App\\Entity\\ArticleFournisseur', NULL, 'Cannot autowire service ".service_locator.84Au0WH": it needs an instance of "App\\Entity\\ArticleFournisseur" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'articleFournisseur' => 'App\\Entity\\ArticleFournisseur',
            'entityManager' => '?',
        ]);
    }
}
