<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WOgy_L8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WOgy.L8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WOgy.L8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'diplomeRepository' => ['privates', 'App\\Repository\\DiplomeRepository', 'getDiplomeRepositoryService', true],
            'domaineRepository' => ['privates', 'App\\Repository\\DomaineRepository', 'getDomaineRepositoryService', true],
            'serviceRepository' => ['privates', 'App\\Repository\\ServiceRepository', 'getServiceRepositoryService', true],
        ], [
            'diplomeRepository' => 'App\\Repository\\DiplomeRepository',
            'domaineRepository' => 'App\\Repository\\DomaineRepository',
            'serviceRepository' => 'App\\Repository\\ServiceRepository',
        ]);
    }
}
