<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleFournisseurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.84Au0WH.App\Entity\ArticleFournisseur' shared service.
     *
     * @return \App\Entity\ArticleFournisseur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.84Au0WH": it needs an instance of "App\\Entity\\ArticleFournisseur" but this type has been excluded in "config/services.yaml".');
    }
}
