<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleFournisseurTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ArticleFournisseurType' shared autowired service.
     *
     * @return \App\Form\ArticleFournisseurType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ArticleFournisseurType.php';

        return $container->privates['App\\Form\\ArticleFournisseurType'] = new \App\Form\ArticleFournisseurType();
    }
}
