<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCVCandidatControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CVCandidatController' shared autowired service.
     *
     * @return \App\Controller\CVCandidatController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CVCandidatController.php';

        $container->services['App\\Controller\\CVCandidatController'] = $instance = new \App\Controller\CVCandidatController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\CVCandidatController', $container));

        return $instance;
    }
}
