<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCvCandidatNoteTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CvCandidatNoteType' shared autowired service.
     *
     * @return \App\Form\CvCandidatNoteType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CvCandidatNoteType.php';

        return $container->privates['App\\Form\\CvCandidatNoteType'] = new \App\Form\CvCandidatNoteType();
    }
}
