<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCVCandidat2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.GUZPG5C.App\Entity\CVCandidat' shared service.
     *
     * @return \App\Entity\CVCandidat
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.GUZPG5C": it needs an instance of "App\\Entity\\CVCandidat" but this type has been excluded in "config/services.yaml".');
    }
}
