<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCVRequirementsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9rVR.mS.App\Entity\CVRequirements' shared service.
     *
     * @return \App\Entity\CVRequirements
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.9rVR.mS": it needs an instance of "App\\Entity\\CVRequirements" but this type has been excluded in "config/services.yaml".');
    }
}
