<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExperienceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.edYJepg.App\Entity\Experience' shared service.
     *
     * @return \App\Entity\Experience
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.edYJepg": it needs an instance of "App\\Entity\\Experience" but this type has been excluded in "config/services.yaml".');
    }
}
