<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHeureSuplementaireService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.K.hq8Wj.App\Entity\HeureSuplementaire' shared service.
     *
     * @return \App\Entity\HeureSuplementaire
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.K.hq8Wj": it needs an instance of "App\\Entity\\HeureSuplementaire" but this type has been excluded in "config/services.yaml".');
    }
}
