<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSectionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9r_lv.j.App\Entity\Section' shared service.
     *
     * @return \App\Entity\Section
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.9r_lv.j": it needs an instance of "App\\Entity\\Section" but this type has been excluded in "config/services.yaml".');
    }
}
