<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSectionReponse2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DqpXpMt.App\Entity\SectionReponse' shared service.
     *
     * @return \App\Entity\SectionReponse
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.DqpXpMt": it needs an instance of "App\\Entity\\SectionReponse" but this type has been excluded in "config/services.yaml".');
    }
}
