<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestResultatService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6m8pwjo.App\Entity\TestResultat' shared service.
     *
     * @return \App\Entity\TestResultat
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6m8pwjo": it needs an instance of "App\\Entity\\TestResultat" but this type has been excluded in "config/services.yaml".');
    }
}
