<?php

namespace ContainerUK4x4yz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestAptitude2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.AGVRq48.App\Entity\TestAptitude' shared service.
     *
     * @return \App\Entity\TestAptitude
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.AGVRq48": it needs an instance of "App\\Entity\\TestAptitude" but this type has been excluded in "config/services.yaml".');
    }
}
