<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUK4x4yz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUK4x4yz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUK4x4yz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUK4x4yz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUK4x4yz\App_KernelDevDebugContainer([
    'container.build_hash' => 'UK4x4yz',
    'container.build_id' => '8ac355fe',
    'container.build_time' => 1700333555,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUK4x4yz');
